### ISSUE TITLE
Selecting Log File Populates the Map File Path

### ISSUE THREAD

**Issue by LinnZawWin** [albanian-xrm/Solution-Packager#2]
Selecting a log file populates the value of the map file path instead of the selected file in the log file dialog.

Steps to repro:
1. Click on Map File button
2. Select an .xml file for map file.
3. The selected Map File path from step 2 appears in the Map File textbox
4. Click on Log File button
5. Select a .txt file for Log File.

**Expected Outcome**
The selected Log File path from step 5 appears in the Log File textbox

**Current Outcome**
The selected Map File path from step 2 appears in the Log File textbox

![Log File Path](https://i.imgur.com/mEUx3Zu.png)

**Comment by BetimBeja** [comment]
Fix pushed. This screenshot is from the latest version installed from `XrmToolBox`.
![image](https://user-images.githubusercontent.com/11160171/103894484-4c279380-50ef-11eb-9dff-91b951495a51.png)
